//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticStore1.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int employee_id { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public System.DateTime hire_date { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> supply_id { get; set; }
        public Nullable<int> payment_id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual payments payments { get; set; }
        public virtual supplies supplies { get; set; }
    }
}
