//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticStore1.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СosmeticsStoreEntities : DbContext
    {
        public СosmeticsStoreEntities()
            : base("name=СosmeticsStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<supplies> supplies { get; set; }
        public virtual DbSet<supply_items> supply_items { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
