//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticStore1.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public int order_item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int quantity { get; set; }
        public decimal price_per_unit { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
